# Generated by Django 2.2 on 2023-04-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='识别名称')),
                ('longitude', models.CharField(max_length=20, verbose_name='经度')),
                ('latitude', models.CharField(max_length=20, verbose_name='纬度')),
                ('image', models.ImageField(null=True, upload_to='map', verbose_name='识别图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '识别信息表',
                'verbose_name_plural': '识别信息表',
                'db_table': 'map',
            },
        ),
    ]
