# Generated by Django 2.2 on 2023-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0002_auto_20230413_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipedia',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
